blogapp_project_root/blogapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.HomeView.as_view(), name='blogapp-home'),
    path('about/', views.about, name='blogapp-about'),
    path('<str:username>/', views.UserPostView.as_view(), name='users_blog'),
    path('post/<int:pk>/', views.PostDetails.as_view(), name='blog_post_detail'),
    path('post/create/', views.CreatePost.as_view(), name='blog-post-create'),
    path('post/<int:pk>/update', views.PostUpdate.as_view(), name='blog-post-update'),
    path('post/<int:pk>/delete', views.PostDelete.as_view(), name='blog-post-delete'),
    path('post/<int:pk>/comment/', views.add_comment, name='add_comments'),
    path('comment/<int:pk>/approve/', views.comment_approve, name='comment_approve'),
    path('comment/<int:pk>/remove/', views.comment_remove, name='comment_remove'),
    path('comment/<int:pk>/edit/', views.comment_update, name='comment_edit'),
]

# views.home returns httpresponse object.

blogapp_project_root/blogapp_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls')),
    path('user/', include('usersapp.urls')),
]

# if we are in debug mode add this url to the urlpatterns
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp_project_root/usersapp/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'usersapp'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('profile/', views.user_profile, name='user_profile'),
    path('login/', auth_views.LoginView.as_view(template_name='usersapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='usersapp/logout.html'), name='logout'),

]

blogapp_project_root/blogapp/models.py
from django.db import models
from datetime import datetime
# import the user model
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.utils.timezone import now
from django.utils import timezone


# Create your models here.
class Post(models.Model):
    header_image = models.ImageField(null=True, blank=True, upload_to="images/")
    title = models.CharField(max_length=100)
    content = models.TextField()
    date = models.DateField(default=datetime.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog_post_detail', kwargs={'pk': self.pk})

    def approved_comments(self):
        return self.comments.filter(approved_comment=True)


class Comments(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    text = models.TextField()
    author = models.CharField(max_length=200)
    created_date = models.DateTimeField(default=timezone.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('blog_post_detail', kwargs={'pk': self.pk})

blogapp_project_root/blogapp/forms.py
from .models import Comments, Post

from django.forms import ModelForm


class CommentForm(ModelForm):
    class Meta:
        model = Comments
        fields = ['author', 'text']

blogapp_project_root/blogapp/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from .models import Post, Comments
from datetime import datetime
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import (ListView,
                                  DetailView,
                                  CreateView,
                                  UpdateView,
                                  DeleteView, )
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from .forms import CommentForm


# Create your views here.
# function base views for listing
def home(request, template_name='blogapp/index.html'):
    return render(request, template_name, {'posts': Post.objects.all(), 'title': 'Home'})


# class based view for listing
class HomeView(ListView):
    model = Post
    context_object_name = 'posts'
    # to order the post from latest to oldest
    ordering = ['-date']
    paginate_by = 4

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            posts = self.model.objects.filter(title__icontains=query)
        else:
            posts = self.model.objects.all()
        return posts


# details view
class PostDetails(DetailView):
    model = Post


# creating new posts
class CreatePost(LoginRequiredMixin, CreateView):
    model = Post
    fields = ['title', 'content', 'header_image']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


# update view

class PostUpdate(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    fields = ['title', 'content']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post_obj = self.get_object()
        if self.request.user == post_obj.author:
            return True
        return False


# delete post
class PostDelete(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = reverse_lazy('blogapp-home')

    def test_func(self):
        post_obj = self.get_object()
        if self.request.user == post_obj.author:
            return True
        return False


# filter posts based on author
class UserPostView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'blogapp/user_posts.html'
    paginate_by = 4

    def get_queryset(self):
        # v try to get the user when v click link on author name in post list
        # to get that user object v do self.kwargs.get('username')
        # self.kwargs is a dictionary of that user datas, and v use get method to fetch username of that user from that dictionary
        # here if user exists in User model v store it in user variable else, return 404 error
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        # now filter the post list based on author and order it by date.
        return Post.objects.filter(author=user).order_by('-date')


def about(request, template_name='blogapp/about.html'):
    return render(request, template_name, {'title': 'About'})


# create a message form
def add_comment(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            return redirect('blog_post_detail', pk=post.pk)
    else:
        form = CommentForm()
    return render(request, 'blogapp/comments_form.html', {'form': form})


@login_required
def comment_approve(request, pk):
    comment = get_object_or_404(Comments, pk=pk)
    comment.approve()
    return redirect('blog_post_detail', pk=comment.post.pk)


@login_required
def comment_remove(request, pk):
    comment = get_object_or_404(Comments, pk=pk)
    comment.delete()
    return redirect('blog_post_detail', pk=comment.post.pk)


# update the comments
def comment_update(request, pk, template_name='blogapp/comments_form.html'):
    comment = get_object_or_404(Comments, pk=pk)
    form = CommentForm(request.POST or None, instance=comment)
    if form.is_valid():
        form.save()
        return redirect('blog_post_detail', pk=comment.post.pk)
    return render(request, template_name, {'form': form})

blogapp_project_root/templates/blogapp/about.html
{% extends 'blogapp/base.html' %}

{% block content %}
<h1>About</h1>
{% endblock %}

blogapp_project_root/templates/blogapp/base.html
<!DOCTYPE html>
{% load static %}
{% load my_templatetag %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB"
    crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/0bcda0c8ae.js"></script>
    <link rel="stylesheet" href="{% static 'blogapp/styles_2.css' %}">
    <title>LinuxCenter</title>
</head>
<body>
       <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-info fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="{% url 'blogapp-home' %}">EducationCentre</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <a class="nav-item nav-link" href="{% url 'blogapp-home' %}">Home</a>
                    <a class="nav-item nav-link" href="{% url 'blog-post-create' %}">New Post</a>

<!--                    <a class="nav-item nav-link" href="{% url 'blogapp-about' %}">About</a>-->
                {% else %}
                    <a class="nav-item nav-link d-none" href="{% url 'blogapp-home' %}">Home</a>
<!--                    <a class="nav-item nav-link d-none" href="{% url 'blogapp-about' %}">About</a>-->
                {% endif %}
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
            <!--to check whether loggined in or logged out-->
<!--                ssearch feature-->
                    {% if request.path == '/' %}
                        <form class="form-inline mr-4" method="GET" action="">
                            <input class="form-control mr-sm-2" name="q" type="search" placeholder="search posts" aria-label="Search" value="{{ request.GET.q }}">
                             <input type="submit" value="Search" class="btn btn-outline-white btn-md my-0 ml-sm-2">

                        </form>
                    {% endif %}
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" href="{% url 'usersapp:user_profile' %}">My Profile</a>
                <a class="nav-item nav-link" href="{% url 'usersapp:logout' %}">Logout</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'usersapp:login' %}">Login</a>
                <a class="nav-item nav-link" href="{% url 'usersapp:register' %}">Register</a>
                {% endif %}

            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container" style="min-height:100vh">
      <div class="row py-5 my-4">
        <div class="col-md-8">
<!--                check if any messages -->
            {% if messages %}
             <div class="container">
            <div class="row">
                <div class="col-md-10 ml-5">
<!--            if messages looop thru it-->
                {% for message in messages %}

                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
                </div>
            </div>
             </div>
            {% endif %}

          {% block content %}
            {% endblock %}


        </div>
        {% if 'login/' in request.path or 'register/' in request.path or 'logout/' in request.path %}
          <div class="col-md-4 py-4 d-none">
              {% sidebar_results %}
          </div>
          {% else %}
            <div class="col-md-4 py-4">
              {% sidebar_results %}
            </div>
          {% endif %}
      </div>
    </main>

       <!-- <footer id="footer-page" style="position:fixed;bottom:0;width:100%">
           <div class="bg-info p-3">
               <p class="text-center text-white">&copy;

<!--                   dynamic year -->
                   <!-- <script type="text/javascript">
                        document.write(new Date().getFullYear());
                    </script>
                   LinuxCentre.com
                   </p>

           </div>
       </footer> --> 



    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T"
    crossorigin="anonymous"></script>

</body>
</html>
`

blogapp_project_root/templates/blogapp/comments_form.html
{% extends 'blogapp/base.html' %}

{% load crispy_forms_tags %}

{% block content %}
<h3 class="text-secondary">Post Comment</h3>
        <div class="form-group">
            <form method="POST" class="post-form">
                {% csrf_token %}
                {{form|crispy}}
                <button type="submit" class="btn btn-info px-4">Post</button>

            </form>

        </div>

{% endblock %}

blogapp_project_root/templates/blogapp/post_confirm_delete.html
{% extends 'blogapp/base.html' %}
{% load crispy_forms_tags %}
{% block content %}

    <section id="logout-section" style="background: gainsboro" class="p-3 mt-3">
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            {{form|crispy}}
        </div>
        <div class=form-group>
            <span>Are You Sure Want to delete this post? </span>
            <button type="submit" class="btn btn-outline-danger ml-2">Delete</button>
            <a href="{% url 'blog_post_detail' object.id %}" class="btn btn-outline-secondary ml-2">Cancel</a>
        </div>
    </form>
        </section>

{% endblock %}

blogapp_project_root/templates/blogapp/post_detail.html
{% extends 'blogapp/base.html' %}


{% block content %}
    <section id="postdetails">
            <div class="card my-3">

                <div class="card-header text-dark">{{object.title}}</a></div>
                <div class="card-body">
<!--                    <h4 class="card-title">{{post.author}}</h4>-->
                    <p class="card-title">{{object.content}}</p>
                    <p><a href="{% url 'users_blog' object.author.username %}">{{object.author}}</a></p>
                    <p>{{object.date|date:"F d, Y"}}</p>
<!--                    if the logged in user is the author of post then -->
                    {% if object.author == user %}
                    <p>
                        <a href="{% url 'blog-post-delete' object.pk %}" class="btn btn-danger">Delete</a>
                        <a href="{% url 'blog-post-update' object.pk %}" class="btn btn-success">Update</a>
                    </p>
                    {% endif %}
                </div>
            </div>
    </section>

    {% if object.author != user %}
        <a href="{% url 'add_comments' pk=post.pk %}" class="btn btn-info">Comment Here</a>
    {% else %}
        <a href="{% url 'add_comments' pk=post.pk %}" class="btn btn-info d-none">Comment Here</a>

    {% endif %}
    {% for comment in post.comments.all %}
        {% if user.is_authenticated or comment.approved_comment %}

    <ul class="list-group list-group-flush pt-3"></ul>
        <div class="comment pb-2 list-group-item">
            <div class="date pb-2">{{comment.created_date}}
            {% if not comment.approved_comment %}
                <a class="btn btn-default" href="{% url 'comment_remove' pk=comment.pk %}"><span class="glyphicon glyphicon-remove">Remove</span></a>
                <a class="btn btn-default" href="{% url 'comment_approve' pk=comment.pk %}"><span class="glyphicon glyphicon-ok">Approve</span></a>
                <a class="btn btn-default" href="{% url 'comment_edit' pk=comment.pk %}"><span class="glyphicon glyphicon-edit">Edit</span></a>
            {% endif %}
            </div>
            <strong>{{comment.author}}</strong>
            <p>{{comment.text}}</p>
        {% endif %}

        </div>
    </ul>
    {% empty %}
        <p class="py-3">No Comments :(</p>
    {% endfor %}

{% endblock %}

blogapp_project_root/templates/blogapp/post_form.html
{% extends 'blogapp/base.html' %}

{% load crispy_forms_tags %}


{% block content %}
<section id="create_post">


                <div class="card">
                    <div class="card-body">

                <form method="POST" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="form-group">
                         <h2 class="text-secondary border-bottom">Add Post</h2>
                        {{form|crispy}}
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-info btn-block">Submit</button>
                    </div>

                </form>
                    </div>
                </div>


</section>
{% endblock %}

blogapp_project_root/templates/blogapp/post_list.html
{% extends 'blogapp/base.html' %}

{% block content %}

    <section id="content">

            {% for post in posts %}
            <div class="card my-5">
              <div class="card-header">
                <img class="rounded-circle float-cleft mr-1" src="{{user.profile.image.url}}" height="40" width="40">
                <a href="{% url 'blog_post_detail' pk=post.pk %}" >{{post.author}}</a>
              </div>
              <img src="{{post.header_image.url}}" alt="...">                                                                                       
                <div class="card-body" height="43" width="40">
                 <p class="card-title"></p>
                </div>
                {{post.content}}
                <div class="card-header">
                  <button type="button" class="btn">{{post.date|date:"F d, Y"}}</button>
                  <a href="{% url 'blog_post_detail' pk=post.pk %}"class="btn">Comments: {{post.approved_comments.count }}</a>
                </div>
                </div>
            {% endfor %}
<!-- pagination -->
 {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4 mt-2" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4 mt-2" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}
                                                                                                                                          
      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4 mt-2" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4 mt-2" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4 mt-2" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4 mt-2" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

 {% endif %}

</section>

{% endblock %}

blogapp_project_root/templates/blogapp/sidebars.html
{% block content %}
<section id="sidebar">

    <h4 class="text-secondary">Latest posts</h4>
 <div class="list-group">
     {% for post in posts %}
        <a href="{% url 'blog_post_detail' post.pk %}" class="list-group-item list-group-item-action list-group-item-info text-dark">
            {{post}}
        </a>
     {% endfor %}
 </div>


</section>

{% endblock %}

blogapp_project_root/templates/blogapp/user_posts.html
{% extends 'blogapp/base.html' %}

{% block content %}
    {% if posts %}

<!--here v get the name of author and count of his post -->
    <h2 class="text-secondary pt-2">Posts by {{view.kwargs.username }}</h2>
        {% for post in posts %}
              <div class="card my-3">

                <div class="card-header"><a href="{% url 'blog_post_detail' post.pk %}" class="text-dark">{{post.title}}</a></div>
                <div class="card-body">
<!--                    <h4 class="card-title">{{post.author}}</h4>-->
                    <p class="card-title">{{post.content}}</p>
                    <p>{{post.date|date:"F d, Y"}}</p>
                </div>
            </div>
        {% endfor %}
    <a href="{% url 'blogapp-home' %}" class="btn btn-secondary px-4">Back</a>
{% else %}
        <div class="alert alert-secondary" role="alert">No Post Yet!</div>

    {% endif %}

<!-- pagination -->
 {% if is_paginated %}

      {% if page_obj.has_previous %}
        <a class="btn btn-outline-info mb-4 mt-2" href="?page=1">First</a>
        <a class="btn btn-outline-info mb-4 mt-2" href="?page={{ page_obj.previous_page_number }}">Previous</a>
      {% endif %}

      {% for num in page_obj.paginator.page_range %}
        {% if page_obj.number == num %}
          <a class="btn btn-info mb-4 mt-2" href="?page={{ num }}">{{ num }}</a>
        {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
          <a class="btn btn-outline-info mb-4 mt-2" href="?page={{ num }}">{{ num }}</a>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <a class="btn btn-outline-info mb-4 mt-2" href="?page={{ page_obj.next_page_number }}">Next</a>
        <a class="btn btn-outline-info mb-4 mt-2" href="?page={{ page_obj.paginator.num_pages }}">Last</a>
      {% endif %}

 {% endif %}


{% endblock %}